input: data/data.csv
num_words: 10000
num_bands: 200
features:
  unique_first_words: true
  word_count: true
  words_per_song: true
  words_per_song_uniq: true
  seconds_per_song: true
  word_rate: true
  word_rate_uniq: true
  types: true
  TTR: true
  logTTR: true
  MTLD: false
  logMTLD: true
  vocd-D: false
  logvocd-D: true
fig_width: 20
fig_height: 10
markersize: 18